version: "3.8"
services:
  mysql8:
    container_name: mysql8
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Sasa2032
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data_mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: sasa2032
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
# If image is uncommented it will download the image from repository
    image: manureq/usuarios
# If build is uncommented it will build the image from docker
#    build:
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./msvc-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  msvc-cursos:
    container_name: msvc-cursos
# If image is uncommented it will download the image from repository
    image: manureq/cursos
# If build is uncommented it will build the image from docker
#    build:
#      context: ./
#      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./msvc-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres14
      - msvc-usuarios
    restart: always

volumes:
  data_mysql:
    name: data_mysql
  data-postgres:
    name: data_postgres

networks:
  spring:
    name: spring
